config/routes.rb
Rails.application.routes.draw do
  
  #Ruta, to => controlador con acción a responder esa "url"
  get 'signup', to: 'users#new' #Registro de usuario.
  get 'login', to: 'sessions#new' #Solicita fórmulario de auth.
  post 'login', to: 'sessions#create' #Evaluación de credenciales
  get 'logout', to: 'sessions#destroy' #Cerrar sesión.

  root 'welcome#index'
  get 'welcome/main'
  get 'welcome/:id' => 'welcome#show'



  resource :users, only: [:new, :create]

 
  resources :patients, except: [:destroy, :show]
  get 'patients/delete'
  get 'patients/destroy' 
  get 'patients/:id' => 'patients#show'
  

    
  resources :diseases
  get 'diseases/:id' => 'diseases#show'
  
  get 'allergies/index'
  resources :allergies
  get 'allergies/:id' => 'allergies#show'
  

  resources :medicines
  get 'medicines/:id' => 'medicines#show'

  resources :substances
  get 'substances/:id' => 'substances#show'

  resources :medical_files

  resources :medical_appointments
  get 'medical_appointments/:id' => 'medical_appointments#show'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    #Validaciones del modelo:
    validates :respuesta, presence: true

    #Relaciones:
    has_many :patients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disease.rb
class Disease < ApplicationRecord
    #Validaciones del modelo:
    validates :respuesta, presence: true

    #Relaciones:
    has_many :patients
end

app/models/medical_appointment.rb
class MedicalAppointment < ApplicationRecord
  #Validaciones del modelo:
  validates :motivo, presence: true
  
  #Relaciones
  belongs_to :patient
end

app/models/medical_file.rb
class MedicalFile < ApplicationRecord
    mount_uploader :foto_expediente , ImagenExpedienteUploader
end

app/models/medicine.rb
class Medicine < ApplicationRecord
    #Validaciones del modelo:
    validates :respuesta, presence: true

    #Relaciones:
    has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
    #Validaciones del modelo:
    validates :nombres, :apellidos, :edad, :fecha_nacimiento, :colonia, :direccion, :celular, presence: true

    #Relaciones:
    belongs_to :user
    belongs_to :disease, required: false
    belongs_to :allergy, required: false
    belongs_to :medicine, required: false
    has_many :medical_appointments

end

app/models/substance.rb
class Substance < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    #self.table_name = "my_table_name"

    #Encriptación de contraseña:
    has_secure_password
    
    #Para indicar que se usaran validaciones:
    validates :email, presence: true, uniqueness: true #Nos indica que será único el email
    validates :name, :password, presence: true

    #Relaciones:
    has_many :patients

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      return redirect_to url_for(:controller => :patients, :action => :new)
    end

    render :new #Si no se guarda llena un arreglo con los errores
  end

  
  private

  #Permite que solo permita los siguientes parámetros
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(key)
        case key
            when 'notice' then 'is-info'
            when 'alert' then 'is-danger'
        end
    end
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/medical_files_helper.rb
module MedicalFilesHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/substances_helper.rb
module SubstancesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/common/_flahs_messages.html.erb
<% flash.each do |key,value|%>
    <div class="notification <%= flash_class(key) %>">
      <%= value %> 
    </div>
  <% end %>

app/views/navegation/_navigation.html.erb
<div class="container">
    
<nav class="navbar is-white" role="navigation" aria-label="main navigation">
<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <a class="" href="">
      <!-- <img src="<=% asset_path '../welcome/Imagenes/logo.jpg' %>" width="112" height="28">-->
      <%= image_tag '/assets/welcome/logo.jpg', size: 120 %>
    </a>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <% if user_signed_in? %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= current_user.name %>
            </a>
            <div class="navbar-dropdown">
              <%= link_to('Salir', logout_path, class: 'navbar-item') %>
            </div>
          </div>
        <% else %>
          <%= link_to('Regístrate', signup_path, class: 'button is-primary') %>
          <%= link_to('Iniciar Sesión', login_path, class: 'button is-light') %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</nav>

</div>

app/views/navigation/_navbar.html.erb
<div class="container">
    
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="" href="">
          <!-- <img src="<=% asset_path '../welcome/Imagenes/logo.jpg' %>" width="112" height="28">-->
          <%= image_tag '/assets/welcome/logo.jpg', size: 120 %>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">

          <a class="navbar-item">
          </a>

          <% if current_user.id == 42 || current_user.id == 45 %>
            <a class="navbar-item" href="/patients">
              Pacientes
            </a>
          <%end%>

        </div>
      </div>


      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if user_signed_in? %>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <%= current_user.name %>
                </a>
                <div class="navbar-dropdown">
                  <%= link_to('Salir', logout_path, class: 'navbar-item button is-danger') %>
                </div>
              </div>
            <% else %>
              <%= link_to('Regístrate', signup_path, class: 'button is-primary') %>
              <%= link_to('Iniciar Sesión', login_path, class: 'button is-light') %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>

</div>